name: 'Terraform Deploy'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

env:
  TF_CLOUD_ORGANIZATION: "arindam"
  TFC_WORKSPACE: "my-terraform-workspace"
  TFC_TOKEN: "${{ secrets.TFC_TOKEN }}"
  GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  APPLY_URL: "https://app.terraform.io/app/arindam/workspaces/my-workspace/runs"

jobs:
  plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Trigger Terraform Plan in Terraform Cloud
        id: tf_plan
        run: |
          RUN_URL=$(curl -s --request POST \
            --header "Authorization: Bearer $TFC_TOKEN" \
            --header "Content-Type: application/vnd.api+json" \
            --data '{
              "data": {
                "attributes": {
                  "message": "GitHub Actions Triggered Plan",
                  "plan-only": true
                },
                "type": "runs",
                "relationships": {
                  "workspace": {
                    "data": {
                      "type": "workspaces",
                      "id": "'"$(curl -s --header "Authorization: Bearer $TFC_TOKEN" \
                      "https://app.terraform.io/api/v2/organizations/$TF_CLOUD_ORGANIZATION/workspaces/$TFC_WORKSPACE" \
                      | jq -r '.data.id')"'"
                    }
                  }
                }
              }
            }' "https://app.terraform.io/api/v2/runs" | jq -r '.data.attributes."web-ui-url"')

          echo "Terraform Plan URL: $RUN_URL"
          echo "PLAN_URL=$RUN_URL" >> $GITHUB_ENV

      - name: Comment Plan URL on PR
        if: github.event_name == 'pull_request'
        run: |
          gh pr comment ${{ github.event.pull_request.number }} \
            --body "Terraform Plan triggered: [$PLAN_URL]($PLAN_URL)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  apply:
    name: 'Terraform Apply'
    needs: plan
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Trigger Terraform Apply in Terraform Cloud
        id: tf_apply
        run: |
          RUN_URL=$(curl -s --request POST \
            --header "Authorization: Bearer $TFC_TOKEN" \
            --header "Content-Type: application/vnd.api+json" \
            --data '{
              "data": {
                "attributes": {
                  "message": "GitHub Actions Triggered Apply"
                },
                "type": "runs",
                "relationships": {
                  "workspace": {
                    "data": {
                      "type": "workspaces",
                      "id": "'"$(curl -s --header "Authorization: Bearer $TFC_TOKEN" \
                      "https://app.terraform.io/api/v2/organizations/$TF_CLOUD_ORGANIZATION/workspaces/$TFC_WORKSPACE" \
                      | jq -r '.data.id')"'"
                    }
                  }
                }
              }
            }' "https://app.terraform.io/api/v2/runs" | jq -r '.data.attributes."web-ui-url"')

          echo "Terraform Apply URL: $RUN_URL"
          echo "APPLY_URL=$RUN_URL" >> $GITHUB_ENV

      - name: Log Apply URL
        run: echo "Terraform Apply triggered ${{ env.APPLY_URL }}"
